name: tasky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  hive: any
  hive_flutter: any
  http: any
  shared_preferences: any
  flutter_svg: any
  google_fonts : any
  crypto: any




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_svg: any
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
